// <auto-generated />
namespace Car
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// <para>Class for car information</para>  
    /// </summary>
    public class Car
    {
        /// <summary>
        /// <para>Store information for car manufacturer</para>  
        /// </summary>
        private string make;

        /// <summary>
        /// <para>Store information for car model</para>  
        /// </summary>
        private string model;

        /// <summary>
        /// <para>Store information for car year of manufacture</para>  
        /// </summary>
        private int year;

        /// <summary>
        /// <para>Store information for car fuel quantity/para> 
        /// </summary>
        private double fuelQuantity;

        /// <summary>
        /// <para>Store information for car fuel consumption/para> 
        /// </summary>
        private double fuelConsumption;


        /// <summary>
        /// Gets or sets validate information for fuel consumption
        /// </summary>
        public double FuelConsumption
        {
            get { return fuelConsumption; }
            set
            {
                if (value < 1)
                {
                    throw new Exception("Car fuel consumption have to be more 1l");

                }
                fuelConsumption = value;
            }
        }

        /// <summary>
        /// Gets or sets validate information for fuel quantity
        /// </summary>
        public double FuelQuantity
        {
            get
            {
                return this.fuelQuantity;
            }
            set { this.fuelQuantity = value; }
        }

        /// <summary>
        /// Gets or sets car year of produced
        /// </summary>
        public int Year
        {
            get
            {
                return this.year;
            }
            set { this.year = value; }
        }

        /// <summary>
        /// Gets or sets a car manufacturer
        /// </summary>
        public string Make
        {
            get { return this.make; }
            set { this.make = value; }
        }

        /// <summary>
        /// Gets or sets car model
        /// </summary>
        public string Model
        {
            get { return this.model; }
            set { this.model = value; }
        }

        /// <summary>
        /// Calculate enough fuel to the final distance
        /// </summary>
        /// <param name="distance"> Set distance to travel</param>
        public void Drive (double distance)
        {
            double neededFuel = distance/100  * this.fuelConsumption;

            if (neededFuel <= this.fuelQuantity)
            {
                this.fuelQuantity -= neededFuel;
            }
            else
            {
                Console.WriteLine("Not enough fuel to perform this trip!");
            }
        }

        /// <summary>
        /// Ask for car name
        /// </summary>
        /// <returns>Return car data in one string</returns>
        public string WhoAmI()
        {

            return $"Make: { this.Make}\nModel: { this.Model}\nYear: { this.Year}\nFuel: { this.FuelQuantity:F2}L";
        }
    }
}
