// <auto-generated />
namespace CarManufacturer
{
    using System;
    using Car;
    /// <summary>
    /// <para>StartUp class for main program</para>  
    /// </summary>
    public class StartUp
    {
        /// <summary>
        /// <para>Main function</para>  
        /// </summary>
        public static void Main()
        {
            Car car = new Car();

            car.Make = "VW";
            car.Model = "MK3";
            car.Year = 1992;
            car.FuelQuantity = 200;
            car.FuelConsumption = 200;
            car.Drive(2000);

            Console.WriteLine(car.WhoAmI());
        }
    }
}
