// <auto-generated />
namespace CarManufacturer
{
    using System;
    using Car;

    /// <summary>
    /// Main program class
    /// </summary>
    public class StartUp
    {
        /// <summary>
        /// Main function
        /// </summary>
        static void Main(string[] args)
        {
            Car car = new Car()
            {
                Make = "VW",
                Model = "MK3",
                Year = 1992,
                FuelQuantity = 200,
                FuelConsumption = 200
            };
            string make = Console.ReadLine();
            string model = Console.ReadLine();
            int year = int.Parse(Console.ReadLine());
            double fuelQuantity = double.Parse(Console.ReadLine());
            double fuelConsumption = double.Parse(Console.ReadLine());
            Car firstCar = new Car();
            Car secondCar = new Car(make,model,year);
            Car thitdCar = new Car(make, model, year,fuelQuantity,fuelConsumption);

        }
    }
}
